### ISSUE TITLE
OpenCL stuff deprecated: first deprecated in macOS 10.14 

### ISSUE THREAD

**Issue by davetapley** [commaai/cereal#138] opened 2021-05-08 00:07 UTC
I hit https://github.com/commaai/openpilot/issues/1358 and did `scons -j4` as suggested there,
but I get `7 errors generated` from deprecation warnings from OpenCL that look like this: 

```
clang++ -o cereal/messaging/bridge cereal/messaging/bridge.o -Lphonelibs/libyuv/mac/lib -L/usr/local/lib -L/opt/homebrew/lib -L/usr/local/opt/openssl/lib -L/opt/homebrew/opt/openssl/lib -L/System/Library/Frameworks/OpenGL.framework/Libraries -Lcereal -Lphonelibs -Lopendbc/can -Lselfdrive/boardd -Lselfdrive/common cereal/libmessaging.a -lzmq -framework OpenCL
cereal/visionipc/visionbuf_cl.cc:48:18: error: 'clCreateCommandQueue' is deprecated: first deprecated in macOS 10.14 - (Define
      CL_SILENCE_DEPRECATION to hide this warning) [-Werror,-Wdeprecated-declarations]
  this->copy_q = clCreateCommandQueue(ctx, device_id, 0, &err);
```

I see a similar things was fixed on https://github.com/commaai/openpilot/pull/1394, does it just need porting here?

**Comment by adeebshihadeh** [comment] 2022-08-21 05:46
Closing since we primarily target Ubuntu 20.04 as described [here](https://github.com/commaai/openpilot/blob/master/tools/README.md#system-requirements), but we're always interested in clean PRs to improve support on other platforms. I couldn't reproduce on my M1 macbook pro; all of openpilot builds fine.

**Closed by adeebshihadeh** 2022-08-21 05:46 UTC
